//
// This is an authoritative DNS server
//

options {
	directory "/var/bind";

	listen-on { any; };

	allow-query { any; };
	allow-query-cache { any; };	

	allow-transfer { none; };

	// If you have problems and are behind a firewall:
	//query-source address * port 53;

	pid-file "/var/run/named/named.pid";
};

zone "lab.local" IN {
	type master;
	file "/etc/bind/db.lab.local";
};

//include "/etc/bind/example.conf";

