//
// This is a cache DNS server
//

options {
	directory "/var/bind";

	listen-on { any;};
	
	allow-query { any; };
	allow-transfer { none; };

	allow-recursion { any;};
	recursion yes;

	forwarders { 192.168.10.10; };
	forward only;

	dnssec-validation no;

	// If you have problems and are behind a firewall:
	//query-source address * port 53;

	pid-file "/var/run/named/named.pid";
};

//zone "COM" { type delegation-only; };
//zone "NET" { type delegation-only; };

// Internet
zone "." IN {
	type hint;
	file "named.ca";
};

// Localhost
zone "localhost" IN {
	type master;
	file "pri/localhost.zone";
	allow-update { none; };
	notify no;
};

// Reverse DNS
zone "127.in-addr.arpa" IN {
	type master;
	file "pri/127.zone";
	allow-update { none; };
	notify no;
};

